# Generated by Django 4.2.1 on 2023-06-15 00:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import artifactmgr.apps.artifacts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('access_expires', models.DateTimeField(blank=True, null=True)),
                ('access_type',
                 models.CharField(choices=[('cookie', 'Cookie'), ('token', 'Token')], default='cookie', max_length=24)),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('cilogon_id', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('fabric_roles',
                 django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255),
                                                           size=None)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('projects',
                 django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255),
                                                           size=None)),
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description_long', models.TextField(max_length=5000)),
                ('description_short', models.CharField(blank=True, max_length=255, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('visibility',
                 models.CharField(choices=[('author', 'Author'), ('project', 'Project'), ('public', 'Public')],
                                  default='author', max_length=24)),
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ArtifactAuthor',
            fields=[
                ('affiliation', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ArtifactTag',
            fields=[
                ('tag',
                 artifactmgr.apps.artifacts.models.LowerCaseField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('tag',),
            },
        ),
        migrations.CreateModel(
            name='ArtifactVersion',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('storage_id', models.CharField(max_length=255)),
                ('storage_repo', models.CharField(max_length=255)),
                ('storage_type', models.CharField(choices=[('fabric', 'FABRIC'), ('git', 'Git'), ('zenodo', 'Zenodo')],
                                                  default='fabric', max_length=24)),
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('artifact',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_version',
                                   to='artifacts.artifact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='version_created_by', to='artifacts.artifactauthor')),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='authors',
            field=models.ManyToManyField(related_name='artifact_authors', to='artifacts.artifactauthor'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='artifact_created_by', to='artifacts.artifactauthor'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='artifact_modified_by', to='artifacts.artifactauthor'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='artifact_tags', to='artifacts.artifacttag'),
        ),
    ]
