"""
Django settings for drf project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import logging
import os
import time
from corsheaders.defaults import default_headers
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


def env_csv(name: str, default: str = '') -> list[str]:
    """Read a comma-separated environment variable as a list of trimmed, non-empty values."""
    return [value.strip() for value in os.getenv(name, default).split(',') if value.strip()]


def dedupe(values: list[str]) -> list[str]:
    """Drop duplicates while preserving order."""
    return list(dict.fromkeys(values))


def env_int(name: str, default: int) -> int:
    """Read an environment variable as an int, tolerating unset, empty and non-numeric values."""
    try:
        return int(os.getenv(name, '').strip())
    except (TypeError, ValueError):
        return default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if os.getenv('DJANGO_SECRET_KEY'):
    SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
else:
    SECRET_KEY = 'django-insecure-=lnekk7th8j+qokv%%05cg%x!&%crul1ka579j04mq&s6(hl3h'

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to false when unset: an unset value must never mean debug, and a bare
# os.getenv(...).casefold() would crash the settings import with an opaque AttributeError
# in any context that does not source .env - `docker compose exec django ...`, for one.
if os.getenv('DJANGO_DEBUG', 'false').casefold() == 'true':
    DEBUG = True
else:
    DEBUG = False

# SECURITY WARNING: don't run with API debug turned on in production!
if os.getenv('API_DEBUG', 'false').casefold() == 'true':
    API_DEBUG = True
else:
    API_DEBUG = False

# Hosts this deployment answers on, as a comma-separated list in .env. Loopback is always
# allowed; a deployment adds its own FQDN and public IPs there rather than editing this file.
ALLOWED_HOSTS = dedupe(['localhost', '127.0.0.1', *env_csv('DJANGO_ALLOWED_HOSTS', '127.0.0.1')])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.postgres',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',  # django cors headers
    'drf_spectacular',
    'django_bootstrap5',  # django bootstrap
    'fontawesomefree',  # fontawesome free version
    'artifactmgr.apps.apiuser',
    'artifactmgr.apps.artifacts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

# Remote servers that call the API cross-site, as a comma-separated list in .env.
CORS_ALLOWED_ORIGINS = dedupe([
    'https://127.0.0.1',
    'https://localhost',
    *env_csv('DJANGO_CORS_ALLOWED_ORIGINS'),
])

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

CORS_ALLOW_HEADERS = (
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "DNT",
    "User-Agent",
    "X-Requested-With",
    "If-Modified-Since",
    "Cache-Control",
    "Range",
)

CORS_AlLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': env_int('REST_FRAMEWORK_PAGE_SIZE', 5),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'PREPROCESSING_HOOKS': ['artifactmgr.server.api_filters.preprocessing_filter_spec'],
    'TITLE': 'FABRIC Artifact Manager',
    'DESCRIPTION': 'A platform for sharing and reproducing FABRIC research artifacts',
    'VERSION': '1.10.1',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
    'COMPONENT_SPLIT_REQUEST': True,
}

ROOT_URLCONF = 'artifactmgr.server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'artifactmgr/templates'),
            os.path.join(BASE_DIR, 'artifactmgr/templates/artifactmgr'),
            os.path.join(BASE_DIR, 'artifactmgr/templates/artifacts'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'artifactmgr.server.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT')
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Logging
# https://docs.djangoproject.com/en/6.0/topics/logging/
#
# Two named loggers are available to first party code through artifactmgr.utils.api_logger:
#   consoleLogger - operational messages, to stdout, relayed by uWSGI into the container logs
#   metricsLogger - the audit event stream, to its own file, never mixed into stdout
#
# Timestamps are UTC in both streams. The converter is set here, at module scope, so that it is
# already in place when uWSGI pre-forks its workers; setting it from a lazily imported module
# would leave startup and migrate records on local time.
logging.Formatter.converter = time.gmtime

# One level per logger - the handlers are opened at DEBUG and the loggers do the gating.
ROOT_LOG_LEVEL = os.getenv('ROOT_LOG_LEVEL', '').strip().upper() or 'WARNING'
DJANGO_LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', '').strip().upper() or 'INFO'
# Pinned separately so DJANGO_LOG_LEVEL=DEBUG cannot also switch on per-query SQL logging.
DJANGO_DB_LOG_LEVEL = os.getenv('DJANGO_DB_LOG_LEVEL', '').strip().upper() or 'INFO'
# Covers consoleLogger and the artifactmgr package logger - the two first party streams.
CONSOLE_LOG_LEVEL = os.getenv('CONSOLE_LOG_LEVEL', '').strip().upper() or 'INFO'
METRICS_LOG_LEVEL = os.getenv('METRICS_LOG_LEVEL', '').strip().upper() or 'INFO'

# Metrics log file. A relative path is resolved against the project root, so the file lands in
# the same place however manage.py is invoked. The directory must already exist and be writable
# by the uWSGI worker uid - dictConfig opens the file at startup and raises if it cannot.
METRICS_LOG_FILE = os.getenv('METRICS_LOG_FILE', '').strip() or 'logs/metrics/metrics.log'
if not os.path.isabs(METRICS_LOG_FILE):
    METRICS_LOG_FILE = os.path.normpath(os.path.join(BASE_DIR, METRICS_LOG_FILE))

# Rotation of the metrics file. 0, the default, selects WatchedFileHandler, which reopens the
# file after an external logrotate has moved it. Any value > 0 selects RotatingFileHandler,
# which rotates in process: opt-in, and local-dev / single-process only. artifactmgr.ini runs
# `processes = 4` with no `lazy-apps`, so all four workers inherit one file description, each
# sees the same offset, and they stampede the rollover - destroying backup generations and
# losing exactly the records an audit is later asked to produce.
METRICS_LOG_MAX_BYTES = env_int('METRICS_LOG_MAX_BYTES', 0)
METRICS_LOG_BACKUP_COUNT = env_int('METRICS_LOG_BACKUP_COUNT', 10)

# delay=False is deliberate: a bad path or a root owned directory then fails loudly at boot,
# instead of silently discarding every audit record at emit time.
_metrics_handler = {
    'level': 'DEBUG',
    'class': 'logging.handlers.WatchedFileHandler',
    'formatter': 'metrics',
    'filename': METRICS_LOG_FILE,
    'delay': False,
    'encoding': 'utf-8',
}
if METRICS_LOG_MAX_BYTES > 0:
    _metrics_handler.update({
        'class': 'logging.handlers.RotatingFileHandler',
        'maxBytes': METRICS_LOG_MAX_BYTES,
        'backupCount': METRICS_LOG_BACKUP_COUNT,
    })

# No datefmt anywhere: supplying one routes asctime through time.strftime, which has no %f and
# would silently drop the milliseconds. The default asctime format keeps them, as ',mmm'.
LOGGING = {
    'version': 1,
    # Load bearing. Django applies DEFAULT_LOGGING first and this dict second; True here would
    # silently disable every third party module logger created up to that point.
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '%(asctime)s [%(levelname)s] [pid:%(process)d] %(name)s : %(message)s',
        },
        'metrics': {
            # Deliberately bare - the metrics grammar is '<Datetime> <Event message>'.
            'format': '%(asctime)s %(message)s',
        },
        'django.server': {
            # Reproduced from DEFAULT_LOGGING so runserver keeps its familiar request lines.
            '()': 'django.utils.log.ServerFormatter',
            'format': '[{server_time}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'formatter': 'default',
        },
        'django.server': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'django.server',
        },
        'metrics': _metrics_handler,
    },
    'root': {
        'handlers': ['console'],
        'level': ROOT_LOG_LEVEL,
    },
    'loggers': {
        # Intended behavior change: DEFAULT_LOGGING attaches a require_debug_true filter to its
        # console handler, so with DJANGO_DEBUG=false Django's own records are invisible in
        # production today. Redefining `django` without that filter means django.request 4xx
        # warnings and 5xx tracebacks now reach stdout in every run mode. That is the point.
        # It also drops DEFAULT_LOGGING's mail_admins handler, which this deployment - with no
        # ADMINS and no mail backend configured - never used.
        'django': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'django.server': {
            'handlers': ['django.server'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': DJANGO_DB_LOG_LEVEL,
            'propagate': False,
        },
        'consoleLogger': {
            'handlers': ['console'],
            'level': CONSOLE_LOG_LEVEL,
            'propagate': False,
        },
        'metricsLogger': {
            'handlers': ['metrics'],
            'level': METRICS_LOG_LEVEL,
            # propagate=False is what stops every audit record from being duplicated into the
            # operational stream.
            'propagate': False,
        },
        'artifactmgr': {
            'handlers': ['console'],
            'level': CONSOLE_LOG_LEVEL,
            'propagate': False,
        },
    },
}

# Storages - Django >= 4.2
# https://docs.djangoproject.com/en/4.2/ref/settings/#storages

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    "fabric_artifact_storage": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": os.getenv('FABRIC_ARTIFACT_STORAGE_DIR'),
            "base_url": "/fabric_artifact_storage/",
            "file_permissions_mode": 0o644,
        },
    },
}

# Artifact download strategy
# False: Django streams the bundle itself with FileResponse. Correct in every run mode and
#        the only option for `--run-mode local-dev`.
# True:  Django authorizes the request, records the download and returns headers only, letting
#        Nginx send the bytes from an internal location via X-Accel-Redirect. The uWSGI worker
#        is released immediately instead of being held for the whole transfer. Requires the
#        bundled Nginx with the same artifact storage directory mounted.
USE_X_ACCEL_REDIRECT = os.getenv('USE_X_ACCEL_REDIRECT', 'false').casefold() == 'true'
X_ACCEL_LOCATION = os.getenv('X_ACCEL_LOCATION', '/protected_artifacts/')

# Login / Logout settings
LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'

LOGOUT_URL = '/logout'
LOGOUT_REDIRECT_URL = '/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'artifactmgr/server/static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
